name: example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  theme_tuner:
    path: ../
  # These should NOT be nested under theme_tuner
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true